global using CleanArchitecture.Application.Common;
global using CleanArchitecture.Application.Common.Interfaces;
global using Polly;
global using Polly.CircuitBreaker;
global using Polly.Fallback;
global using Polly.Retry;
global using CleanArchitecture.Infrastructure.SmsProvider;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;